name: sam6d
channels:
  - xformers
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pip
  #- python=3.9.6
  - python=3.12
  - pip:
    - torch==2.3.1 # be careful when updating this version, torchvision and xformers need to also match, including CUDA support
    - torchvision==0.18.1
    - fvcore
    - xformers==0.0.27
    - torchmetrics==0.10.3
    - blenderproc==2.6.1
    - opencv-python 
    # ISM 
    - omegaconf
    - ruamel.yaml
    - hydra-colorlog
    - hydra-core
    - gdown
    - pandas
    - imageio
    - pyrender
    - pytorch-lightning==1.8.6 # previous versions are not compatible with pip version >23.x
    - pycocotools 
    - distinctipy
    - git+https://github.com/facebookresearch/segment-anything.git  # SAM
    - ultralytics==8.0.135  # FastSAM
    # PEM
    - timm
    - gorilla-core==0.2.7.8
    - trimesh==4.4.1
    - gpustat==1.0.0
    - imgaug
    - einops